/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class inaos_NativeDispatcher */

#ifndef _Included_inaos_NativeDispatcher
#define _Included_inaos_NativeDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     inaos_NativeDispatcher
 * Method:    exec
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_inaos_NativeDispatcher_exec
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
